### PR TITLE
Issue #581

### PR DESCRIPTION
**Pull request by jmmclean**
Added a post functionality for FB.api as per doc reference below. Functionality may be incomplete as it may request further dev to android/ios native code

SRC: https://developers.facebook.com/docs/javascript/reference/FB.api

Issue Ref #581

### CODE REVIEW

**Comment by gpinkham** [comment]
any reason why this shouldn't be merged in?

**Comment by jmmclean** [comment]
@gpinkham - unfortunately, i know this is an incomplete PR, I was hoping someone w/ Native expertise could finish it up.

Also, Im not sure this is actually needed. To accomplish a POST method, all you need to do is something similar to the below:
```
this.fb.api(`/${pid}/feed?method=post&message=${body.message}&place=${body.place}&access_token=${token}`,['publish_pages'])
```
Notice, the API supports calling `method=post` then defining the body. the above is a verified working sample to post to a business page.

**Comment by gpinkham** [comment]
@jmmclean thanks!   that is exactly what I needed..     already was using an older version of the plugin due to constraints by other plugins..

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. That plugin supports GET, POST, and DELETE requests.

**Pull request closed without merging**
