### PR TITLE
Fix openUrl handling bugs and add support for cordova-ios-5

### PR DESCRIPTION
**Pull request by guylando**
Fix https://github.com/jeduan/cordova-plugin-facebook4/issues/750

### CODE REVIEW

**Comment by GexxOn** [comment]
oh, just saw this PR - we ran into exactly the same issue and also discovered the same solution. pLease merge this!! (or ours ;))

**Comment by guylando** [comment]
This now also fixes #770 by updating facebook android AND ios sdks to version 5.0.2.
If someone wants to use my fork (https://github.com/guylando/cordova-plugin-facebook4) until it gets merged then run:
`cordova plugin remove cordova-plugin-facebook4`
`cordova plugin add https://github.com/guylando/cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication"`
replace 123456789 with your app id and myApplication with your app name

**Comment by igorkurochka** [comment]
@guylando I've installed your fork and am getting crash on iOS, looks like handling openURL never ends, I've got thousands of this message in xcode console before it crashes:
2019-06-17 09:14:51.592862+0300 My Project[575:95449] FB handle url using application:openURL:options: fb54303189618000://authorize#access_token=...&data_access_expiration_time=1568528083&denied_scopes=&expires_in=5120025&granted_scopes=email%2Cpublic_profile&signed_request=...&state=%7B%22challenge%22%3A%22rgvXLvVXtmApSpc1hxQ5I3gk3U4%253D%22%2C%220_auth_logger_id%22%3A%2233AA6FF6-055E-4BD7-87A8-AE185A4BBD15%22%2C%22com.facebook.sdk_client_state%22%3Atrue%2C%223_method%22%3A%22sfvc_auth%22%7D

any ideas how to fix?

**Comment by guylando** [comment]
@igorkurochka did you do this https://github.com/jeduan/cordova-plugin-facebook4/issues/750#issuecomment-466036388 ?

**Comment by gustavokloh** [comment]
Hey maintainers :D 
Do you will merge this PR? It will help a lot.

Thanks!

**Comment by HodayaGruzman** [comment]
hey, I really need that pr too.
please merge it, I need it for facebook android AND ios sdks to version 5.0.2.

**Comment by vvarda** [comment]
@guylando installing this fork stucks.

`cordova plugin add https://github.com/guylando/cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication"`
or
`npm install --save https://github.com/guylando/cordova-plugin-facebook4.git`

What's the problem? Another npm-packages or cordova-plugins install normally.

**Comment by guylando** [comment]
@vvarda this plugin is huge so it takes a lot of time, just leave it and go eat something

**Comment by peterpeterparker** [comment]
thx @guylando for the amazing work 👍

**Pull request merged**
