### PR TITLE
Adding Facebook suffix for iOS

### PR DESCRIPTION
**Pull request by vomchik**
Adding Facebook suffix for correct redirect back to app if uses one facebook id for differents applications.

### CODE REVIEW

**Comment by jeduan** [comment]
@vomchik thanks! Can you add docs for this?

**Comment by vomchik** [comment]
Yes, but a little bit later.

**Comment by jeduan** [comment]
no rush 😄

**Comment by vomchik** [comment]
Okay!

**Comment by marcosseki** [comment]
@jeduan any possibility to accept these commits?

This is the solution for multiple apps using same Facebook App Id. Sometimes the callback runs on the wrong app. 😄

**Comment by jeduan** [comment]
@marcosseki can you? Let me know if you’re interested in maintaining this repo.

**Comment by peterpeterparker** [comment]
Unfortunately this PR can't be merged. Using suffix for scheme URL should be optional, unfortunately adding a preference like

     <preference name="URL_SCHEME" />

or 

     <preference name="URL_SCHEME" default="" />

make the variable `URL_SCHEME` mandatory for the command `cordova plugin add..."

furthermore than behind optional, the solution should also not add `FacebookUrlSchemeSuffix` to `-Info.plist` in case nothing would be defined (as it is now)

Therefore I reject this PR. 

I understand the need of the features, so plz anyone feel free to submit a new PR related to the issue I opened about this respectively https://github.com/jeduan/cordova-plugin-facebook4/issues/654

P.S.: For the record, command and stacktrace

> cordova plugin add /Users/me/cordova-plugin-facebook4-fork --variable APP_ID=123456789 --variable APP_NAME=myApplication --save
> 
> (node:1065) UnhandledPromiseRejectionWarning: CordovaError: Variable(s) missing (use: --variable URL_SCHEME_SUFFIX=value).
>     at Object.mergeVariables (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/plugin/util.js:77:15)

**Pull request closed without merging**
