### PR TITLE
Enabling post request for graph api

### PR DESCRIPTION
**Pull request by nomadongho**

### CODE REVIEW

**Comment by aelx311** [comment]
When will this be merged?

**Comment by agittm** [comment]
not work for me, here's my code

facebookConnectPlugin.api(
    '/me/photos?post&url=...', 
    ['publish_actions'], 
    function onSuccess(result){
        console.log(result);
    }, 
    function onError(error){
        console.log(error);
    }
);

onSuccess is called but return 0.

**Comment by dcooldrummer** [comment]
Is this going to be merged? Or does anyone know of a workaround for this? Trying to use API for post

**Comment by noahcooper** [comment]
This plugin is deprecated. See `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. That plugin supports both POST and DELETE.

**Pull request closed without merging**
