### PR TITLE
Update facebook sdk versions

### PR DESCRIPTION
**Pull request by Morathil**
Update facebook sdk versions for android and ios

### CODE REVIEW

**Comment by Silvercast** [comment]
@jeduan can you merge this as I hope this would solve issue of blank safari view controller on SDK 4.7 iOS 9? A bit urgent please :)

http://i.stack.imgur.com/EajPf.png

http://stackoverflow.com/questions/33499905/ios-facebook-blank-white-screen-after-app-is-authorized

**Comment by Silvercast** [comment]
not really, I still have blank screen after manually updating Facebook SDK on iOS. have to fallback to use old SDK version :(

**Comment by Alexandre-io** [comment]
+1

**Comment by ripcurlx** [comment]
+1

**Comment by vivekpd15** [comment]
+1

**Comment by clarkgiguiere** [comment]
+1

**Comment by joshuarh** [comment]
There is a more recent release of the SDKs since this PR was created. I've created a PR @ https://github.com/jeduan/cordova-plugin-facebook4/pull/218 which also supports quote sharing via the share dialog.

**Comment by clarkgiguiere** [comment]
@joshuarh thanks.

**Comment by robertarnesson** [comment]
https://github.com/jeduan/cordova-plugin-facebook4/commit/61d454c278eec12a66d05f3337303d280cc6bf77

**Pull request closed without merging**
