### PR TITLE
Fix for directory structure whatever cordova-android version.

### LINKED ISSUE #599: cordova-android@7.0.0 incompatibility
Hi,

It looks like `cordova-plugin-facebook4` isn't compatible with `cordova-android` **7.0.0**

I'm guessing that the incompatibility source is the following element in `plugin.xml`

      <config-file target="AndroidManifest.xml" parent="application">
            <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/fb_app_id"/>
            <meta-data android:name="com.facebook.sdk.ApplicationName" android:value="@string/fb_app_name" />
            <activity android:name="com.facebook.FacebookActivity"
              android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
              android:label="@string/fb_app_name" />
        </config-file>

Regarding what was indicated in https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

Steps to reproduce:

     ionic start cordova-7
     ionic cordova platform add cordova-android@7.0.0
     ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication"
     ionic cordova build android

Thx in advance for any help

Stacktrace:

> 
> BUILD FAILED in 12s
> 25 actionable tasks: 4 executed, 21 up-to-date
> Error: /Users/me/Documents/projects/test/cordova-7/platforms/android/gradlew: Command failed with exit code 1 Error output:
> /Users/me/Documents/projects/test/cordova-7/platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:112: AAPT: error: resource string/fb_app_id (aka io.ionic.starter:string/fb_app_id) not found.
>     
> /Users/me/Documents/projects/test/cordova-7/platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:115: AAPT: error: resource string/fb_app_name (aka io.ionic.starter:string/fb_app_name) not found.
>     
> /Users/me/Documents/projects/test/cordova-7/platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:119: AAPT: error: resource string/fb_app_name (aka io.ionic.starter:string/fb_app_name) not found.
>     
> /Users/me/Documents/projects/test/cordova-7/platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:112: error: resource string/fb_app_id (aka io.ionic.starter:string/fb_app_id) not found.
> /Users/me/Documents/projects/test/cordova-7/platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:115: error: resource string/fb_app_name (aka io.ionic.starter:string/fb_app_name) not found.
> /Users/me/Documents/projects/test/cordova-7/platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:119: error: resource string/fb_app_name (aka io.ionic.starter:string/fb_app_name) not found.
> error: failed processing manifest.
> 
> Failed to execute aapt
> com.android.ide.common.process.ProcessException: Failed to execute aapt
> 	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
> 	at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
> 	at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
> 	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
> 	at sun.reflect.GeneratedMethodAccessor313.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
> 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
> 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
> 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
> 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
> 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
> 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
> 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
> 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
> 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
> 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
> 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
> 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
> 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
> 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
> 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
> 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
> 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
> 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
> 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
> 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
> 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
> 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
> 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
> 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
> 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
> 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:482)
> 	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
> 	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:794)
> 	... 47 more
> Caused by: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
> 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
> 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:462)
> 	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
> 	at com.android.builder.internal.aapt.v2.QueueableAapt2.lambda$makeValidatedPackage$1(QueueableAapt2.java:179)
> Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
> 	at com.android.builder.png.Aap
> [ERROR] An error occurred while running cordova build android (exit code 1).

### PR DESCRIPTION
**Pull request by kevin-lot**
Fixes #599
Update plugin.xml.
`<config-file>` interperts correctly path for AndroidManifest.xml, strings.xml and config.xml whatever version of directory structure.
I just remove facebookconnect.xml and move values inside strings.xml.

Tested with facebook connection under cordova-android-7.

note: Apply standardjs fixes on after_prepare.js too (sorry about that).

### CODE REVIEW

**Comment by fredgalvao** [comment]
Don't take my question personally, I'm just trying to simplify things:
Considering my personal opinion, which some online sources agree with, that `strings.xml` should not be modified by a plugin, but only by a user or a localization process/tool, and also considering that https://github.com/jeduan/cordova-plugin-facebook4/pull/601 already aims at fixing the same issue successfully, why do we need this PR over that one?

**Comment by kevin-lot** [comment]
Sorry, for the misunderstanding. I thought that the PR #601 did not solve the problem because it is not compatible with earlier versions of Cordova-android.
It dates from December 9 and is still waiting. So I thought you wanted extra compatibility.

**Comment by fredgalvao** [comment]
That's actually a very good point (extra backwards compatibility). That makes this a valid alternative to the original PR.

As for the delay there, it's just that there isn't that many active developers available to help maintain this plugin right now, so it's just fair that it takes a while for things to move. Jeduan has offered to transfer ownership of the repo to someone willing to lead maintenance, but we haven't had someone say "Pick me!" yet, which is sad.

**Comment by sebj54** [comment]
I confirm it works! I made a custom manual diff patch of this PR and added the plugin from a local copy.
The only tweak I had to do was running app with this command:

```
cordova run android -- --minSdkVersion=16
```

Like you said, it is really sad that there is not even one Cordova plugin for Facebook Login actually maintained :(

**Comment by akhatri** [comment]
Hi guys - thanks for attempting to get this working for the new Android version :)

I just tried this PR version but it doesnt work on my project. I'm not sure if its something to do with my setup. Its identical to this issue on SO https://stackoverflow.com/questions/48706617/ionic-2-app-build-fail-after-install-facebook-login-plugin.

Adding these manually in the xml file works but I'm not sure if it will work this way as this folder is always re-built.

My system information

```
cli packages:

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.1
    npm               : 5.6.0
    OS                : Windows 10
```

I've tried to play around with the paths within the config.xml file too but no luck. The new paths as per tha latest cordova android is `platforms/android/app/src/main/res/values/strings.xml`

**Comment by peterpeterparker** [comment]
@akhatri see the documentation, chapter "cordova-android >= 7"

https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/android/README.md

**Comment by akhatri** [comment]
Hi @peterpeterparker it's working now :) I had to remove the Android platform and then build the project so it took the config settings. Previously the project was already built so it appears that it didn't override it.

when can we merge this PR into the master branch? Would be great to get this plugin working on our project.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. That plugin requires cordova-android 7, so does not need to worry about the different directory structures of older Android versions anymore.

**Pull request closed without merging**
