### PR TITLE
Updates facebook JS SDK

### PR DESCRIPTION
**Pull request by karlAlnebratt**
Adds config options for  `FACEBOOK_BROWSER_SDK_VERSION `

### CODE REVIEW

**Comment by peterpeterparker** [comment]
Hi @karlAlnebratt

Thx for the PR, I noticed two errors. I'm happy to merge it if you correct them.

1. There is a typo

Respectively 

```
FB.init({
       appId      : APP_ID,  // APP_ID is populated by the cordova after_prepare hook		       appId      : APP_ID,  // APP_ID is populated by the cordova after_prepare hook
       xfbml      : true,		       xfbml      : true,
       version    : 'v2.7'		       version    : 'FACEBOOK_BROWSER_SDK_VERSION'
     });		     });
```

`'FACEBOOK_BROWSER_SDK_VERSION'` should not be a string but the variable, like `FACEBOOK_BROWSER_SDK_VERSION` (without `''`)

2. Unfortunately the script doesn't inherit the default value (v3.2) set in `plugin.xml` as this value isn't copied to `config.xml`. For that reason, if the user doesn't provide the `--variable FACEBOOK_BROWSER_SDK_VERSION=""` in his/her cmd line the value will be set to `null` which obviously we don't want respective we do want the default value to be used and not to "force" all user to add the parameter to their command line.

Thx in advance for the improvements

**Comment by karlAlnebratt** [comment]
@peterpeterparker 
I'll be happy to fix the issues.
1. where is the typo?

2. how do you prefer that we get the default value? 
 - Should we get it from the `plugin.xml` in `node_modules`

3. The `FACEBOOK_BROWSER_SDK_VERSION` as a variable, since the facebook sdk version is a `String`. We need to wrapp the `FACEBOOK_BROWSER_SDK_VERSION` with `"` 
 - Do you suggest doing this in the `scripts/after_prepare.js`
```javascript
contents.replace(/FACEBOOK_BROWSER_SDK_VERSION/g, `'${FACEBOOK_BROWSER_SDK_VERSION}'`)
```

**Comment by peterpeterparker** [comment]
@karlAlnebratt 

- typo and last question: in `facebook-browser.js` replace `'FACEBOOK_BROWSER_SDK_VERSION'` with `FACEBOOK_BROWSER_SDK_VERSION`, I think it just works fine, give a try

- not from `node_modules`, doesn't sound like the solution. for example in my case plugins are installed under `./plugins`. probably something relative to where the build happens

**Comment by karlAlnebratt** [comment]
@peterpeterparker about the 2.
When I run `cordova plugin add cordova-plugin-facebook4@git@github.com:apprl/cordova-plugin-facebook4.git --save --variable APP_ID="177090790853" --variable APP_NAME="APPRL"`

My config looks like this after.
```
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.example.hello" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloWorld</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <engine name="browser" spec="~5.0.4" />
    <plugin name="cordova-plugin-facebook4" spec="git+ssh://git@github.com/apprl/cordova-plugin-facebook4.git">
        <variable name="APP_ID" value="123" />
        <variable name="APP_NAME" value="TEST" />
        <variable name="FACEBOOK_HYBRID_APP_EVENTS" value="false" />
        <variable name="FACEBOOK_ANDROID_SDK_VERSION" value="4.40.0" />
        <variable name="FACEBOOK_BROWSER_SDK_VERSION" value="v3.2" />
    </plugin>
</widget>
```
So it adds the `<variable name="FACEBOOK_BROWSER_SDK_VERSION" value="v3.2" />` to the cordova config.xml.

Isn't it cleaner if we get the default value from `config.xml` same as with `APP_ID`

**Comment by peterpeterparker** [comment]
@karlAlnebratt have a look at my first comment again. I had the value set in my `config.xml` and after build this value wasn't used. I ended up having a value `null` instead of `v3.2` in the browser 

-> variable in config.xml -> bundle output = null
-> variable passed in the cmd line (cordova build --variable...) -> bundle output = v3.2

**Comment by karlAlnebratt** [comment]
I have change the `FACEBOOK_BROWSER_SDK_VERSION` to a string  [5c52a99](/jeduan/cordova-plugin-facebook4/pull/742/commits/5c52a99787f4d5d4cb4317f04ecd65baa8aa8d31)

For me if I install the plugin it works as expected. Here are the steps I did. Could you describe in detail how you do to get the `null` value

### No config added on plugin install
1. `cordova create hello com.example.hello HelloWorld`
2. `cd hello`
3. `cordova platform add browser`
4. `cordova plugin add cordova-plugin-facebook4@git@github.com:apprl/cordova-plugin-facebook4.git --save --variable APP_ID="123" --variable APP_NAME="TEST"`
5.
```
cat config.xml | grep FACEBOOK_BROWSER_SDK_VERSION
<variable name="FACEBOOK_BROWSER_SDK_VERSION" value="v3.2" />
```
6.
```
cat platforms/browser/www/plugins/cordova-plugin-facebook4/www/facebook-browser.js | grep after_prepare
appId      : APP_ID,  // APP_ID is populated by the cordova after_prepare hook
version    : FACEBOOK_BROWSER_SDK_VERSION // FACEBOOK_BROWSER_SDK_VERSION is populated by the cordova after_prepare hook
```
7. `cordova prepare browser`
8.  
```
cat platforms/browser/www/plugins/cordova-plugin-facebook4/www/facebook-browser.js | grep after_prepare
appId      : 123,  // 123 is populated by the cordova after_prepare hook
version    : 'v3.2' // 'v3.2' is populated by the cordova after_prepare hook
```
---

###  Add config to plugin install
1. `cordova create hello com.example.hello HelloWorld`
2. `cd hello`
3. `cordova platform add browser`
4. `cordova plugin add cordova-plugin-facebook4@git@github.com:apprl/cordova-plugin-facebook4.git --save --variable APP_ID="123" --variable APP_NAME="TEST" --variable FACEBOOK_BROWSER_SDK_VERSION="v2.7"`
5.
```
cat config.xml | grep FACEBOOK_BROWSER_SDK_VERSION
<variable name="FACEBOOK_BROWSER_SDK_VERSION" value="v2.7" />
```
6.
```
cat platforms/browser/www/plugins/cordova-plugin-facebook4/www/facebook-browser.js | grep after_prepare
appId      : APP_ID,  // APP_ID is populated by the cordova after_prepare hook
version    : FACEBOOK_BROWSER_SDK_VERSION // FACEBOOK_BROWSER_SDK_VERSION is populated by the cordova after_prepare hook
```
7. `cordova prepare browser`
8.  
```
cat platforms/browser/www/plugins/cordova-plugin-facebook4/www/facebook-browser.js | grep after_prepare
appId      : 123,  // 123 is populated by the cordova after_prepare hook
version    : 'v2.7' // 'v2.7' is populated by the cordova after_prepare hook
```

**Comment by peterpeterparker** [comment]
@karlAlnebratt thx for the details, I don't know I still got `null` :( 

maybe I do something wrong, feel free to correct me, I did the following:

```
cd /Users/me/projects/lab/
git clone https://github.com/apprl/cordova-plugin-facebook4.git
ionic start facebook4-test --type=angular
cd facebook4-test/
ionic cordova plugin add /Users/me/projects/lab/cordova-plugin-facebook4 --save --variable APP_ID="123" --variable APP_NAME="TEST"
ionic cordova platform add browser
less platforms/browser/platform_www/plugins/cordova-plugin-facebook4/www/facebook-browser.js
```

results:

```
...
if (window.location.protocol === "file:") {
  console.warn("Facebook JS SDK is not supported when using file:// protocol");
} else {
  window.fbAsyncInit = function() {
    FB.init({
      appId      : 123,  // 123 is populated by the cordova after_prepare hook
      xfbml      : true,
      version    : 'null' // 'null' is populated by the cordova after_prepare hook
    });
...
```

**Comment by karlAlnebratt** [comment]
@peterpeterparker Thanks. I did not test it with `Iconc` will do that. And get back to you

**Comment by vvarda** [comment]
@karlAlnebratt @peterpeterparker guys, what with that PR? Should it be merged maybe?

**Comment by peterpeterparker** [comment]
I don't maintain the plugin anymore since March 2020 (https://github.com/jeduan/cordova-plugin-facebook4/issues/629#issuecomment-605059536) therefore unfortunately can't help here.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect`. I've incorporated the PR from @karlAlnebratt and the new `FACEBOOK_BROWSER_SDK_VERSION` preference is now available on the browser platform.

https://www.npmjs.com/package/cordova-plugin-facebook-connect

**Pull request closed without merging**
