### PR TITLE
Urgent - IOS crash when enableHybridAppEvents is enabled #745

### PR DESCRIPTION
**Pull request by regevbr**
Urgent - IOS crash when enableHybridAppEvents is enabled #745

### CODE REVIEW

**Comment by peterpeterparker** [comment]
@regevbr Thx for the PR, don't have time before tonight but could have a look later

And Android, something to do?

**Comment by regevbr** [comment]
It works on android just fine.
The problem occurs in the WKWebView only which enforces that no 2 script handlers will have the same name.

**Comment by regevbr** [comment]
I do believe that the issue should really be fixed in the Facebook SDK but it will take forever to be fixed there. I will open an issue on their side as well

**Comment by peterpeterparker** [comment]
Thx for the confirmation 👍

I'll merge this and release a fix tonight

If u still have time to try v4.1.0 as discussed that would be interesting, I'm asking myself if the issue is here since a bit or if it's related to the Facebook SDK upgrade, as they, Fb, doesn't display anything in their Changelog

**Comment by regevbr** [comment]
Sure thing.
Haha I will check later on today.
In any case here is the bug report in facebook - 
https://developers.facebook.com/bugs/242837016595902/

**Comment by regevbr** [comment]
@peterpeterparker this fails exactly the same in 4.1.0

**Comment by peterpeterparker** [comment]
@regevbr thx a lot for the feedback, I'm almost happy to hear that 😉

I check the rest tonight

**Comment by peterpeterparker** [comment]
PR has been merged and a new version of the plugin has been released to npm

thx @regevbr for the PR, quick fix and clearing that up with Facebook 👍 

FYI @msencer this fix an issue which follows your PR https://github.com/jeduan/cordova-plugin-facebook4/pull/732

**Pull request merged**
