### PR TITLE
Coexist with inAppBrowser plugin (fixed)

### PR DESCRIPTION
**Pull request by DanielRiera**

### CODE REVIEW

**Comment by tgensol** [comment]
@DanielRiera On my side I never had issue with InAppBrowser plugin, could you tell when the issue happens ?

**Comment by DanielRiera** [comment]
@tgensol If not have Facebook app, Facebook SDK use window.open for users login, inAppBrowser replace this function and generate a error, allways i have this error.

**Comment by tgensol** [comment]
@DanielRiera I tried both with Facebook app or not, and it is working well on my side. (ios 10.3 and 11)
Where does it happen ? On ios ? Android ? Which cordova do you have ?

Thanks

**Comment by DanielRiera** [comment]
@tgensol I use Phonegap 7.0.1, but have this error from before versions.
This happen in Android and iOS, on my case, only work well when use this pull.

I'm going to do a simulation and upload some screenshot

**Comment by DanielRiera** [comment]
@tgensol This is error

> Refused to display 'https://m.facebook.com/login.php?skip_api_login=1&api_key=.......' in a frame because it set 'X-Frame-Options' to 'deny'.
InAppBrowserProxy.js:42 Uncaught DOMException: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:3000/plugins/cordova-plugin-inappbrowser/src/browser/InAppBrowserProxy.js:42:71)

I solved with this pull

**Comment by DanielRiera** [comment]
Several open problems #546 #380 #368 #323

**Comment by noahcooper** [comment]
`cordova-plugin-inappbrowser` no longer clobbers `window.open`, so this is now moot.

This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

**Pull request closed without merging**
