### PR TITLE
Updated logPurchase to handle decimal values correctly.

### PR DESCRIPTION
**Pull request by MichaelMalony**
Resolves issues #493. 

On Android (java) the logPurchase value parameter comes through as either Integer or Double depending on if the original js/ts number has a decimal. Updated logPurchase method to pull correct type out of args array (include Long & String as well).

### CODE REVIEW

**Comment by fredgalvao** [comment]
If it's converted to a `BigDecimal` everytime anyway, couldn't we just get it as a `String` everytime and let the `BigDecimal` constructor deal with the required precision?

**Comment by MichaelMalony** [comment]
> If it's converted to a BigDecimal everytime anyway, couldn't we just get it as a String everytime and let the BigDecimal constructor deal with the required precision?

new BigDecimal(args.getString(0)) would probably cover all cases. Though at that point you're going to be grabbing an int/double, converting that to a string, then converting that to a BigDecimal.

There's some precision implications between the two approaches: http://stackoverflow.com/questions/29632454/new-bigdecimaldouble-vs-new-bigdecimalstring

**Comment by fredgalvao** [comment]
Interesting point. However, isn't that another in favor of going through string everytime? It eliminates imprecisions in fluctuating precision and simplifies the code, alltogether.

**Comment by MichaelMalony** [comment]
Updated to use 
`BigDecimal value = new BigDecimal(args.getString(0));`
for all types.

**Pull request merged**
