### PR TITLE
Fix issue when using with InAppBrowser on ios9

### PR DESCRIPTION
**Pull request by NGumby**

### CODE REVIEW

**Comment by jeduan** [comment]
Thanks for your PR!

Can you provide more info on the InAppBrowser mode?

**Comment by NGumby** [comment]
This is how I create my InAppBrowser :
```
appBrowser = window.open(urlLogin, '_blank', 'location=no,toolbar=no,hidden=yes,toolbarposition=top,disallowoverscroll=yes,enableViewportScale=yes');
```
By the way, in the contribution guide for a pull request, it says to use the Develop branch which doesn't exist.

**Comment by jeduan** [comment]
Don't know about this approach, shouldn't we be calling something like `[self dismissViewControllerAnimated:YES completion:nil]`? Why are those extra calls every time we call something the best path?

**Comment by NGumby** [comment]
This probably isn't the best approach, since my knowledge of ios and objective C is basically debugging and trying to fix cordova plugins when something isn't working like I need it to.  

All I know is that ```self.viewController``` isn't on top in certain cases, and because of that it won't render the facebook window.  And calling ```topMostController``` makes sure that it uses a valid controller for the calls.  I'm open to any other solution, especially if we don't need to go through the loop for every call.

**Comment by chooseapp** [comment]
Any idea for that issue ? Not sure if it is inappbrowser plugin, because I tried with and without it, but on iOS, the plugin is always opening Safari. 

Thanks

**Pull request merged**
