### PR TITLE
Added hashtag support

### PR DESCRIPTION
**Pull request by mpk2**
Just adds a hashtag if you specify the hashtag as an argument in the options objects for the share method.

*Ex.*
```
var options = {
                    method: "share",
                    href: "https://mysite.com",
                    hashtag: "#myHashtag"
                };

facebookConnectPlugin.showDialog(options, function(s){}, function(f){});
```

### CODE REVIEW

**Comment by jeduan** [comment]
@mpk2 Can you add documentation for this?

**Comment by mpk2** [comment]
@jeduan do you mean in the main README?

**Comment by jeduan** [comment]
yep

**Comment by mpk2** [comment]
Looking at the README, this seems to be consistent with the other available options now.

**Comment by thezakman** [comment]
Is possible to add more than one hashtag?

**Comment by mpk2** [comment]
@thezakman to the best of my knowledge, no. I don't believe the facebook share API supports more than one being set.

**Comment by thezakman** [comment]
Thank you @mpk2

**Pull request merged**
