### PR TITLE
Grab APP_ID from package.json

### PR DESCRIPTION
**Pull request by keyz182**
The simple parsing of `config.xml` lead to the code picking up the `APP_ID` from cordova-plugin-ionic  when installed, instead of the configuration from this plugin. Parsing the JSON instead allows us to navigate to the correct plugin, without having to load an XML parser or similar.

### CODE REVIEW

**Comment by peterpeterparker** [comment]
Hi @keyz182 

Thx for the PR

1. Are you 100% sure that every single user of the plugin (not "just" the Ionic users) have the information you are looking for, `APP_ID`, in a `package.json` and not `config.xml` (since your PR change the source of the information I've to ask)? I specially thinking about PhoneGap users or users using Cordova-android < 7

2. Could you plz provide more details about how to reproduce the error (ionic start..., ionic cordova add and npm install ..., etc.). To validate the PR I would like first to reproduce the error before trying with your patch

Thx in advance for these details

**Comment by keyz182** [comment]
1) My understanding is that anything using cordova@7+ will have a package.json (https://cordova.apache.org/news/2017/05/04/cordova-7.html) - so this would be incompatible with cordova 6 and earlier. It should have no relevance on cordova-android and other platform packages.

2) I'll sort that out shortly.

**Comment by peterpeterparker** [comment]
1. Ummmm we might have to think about it I think. I kind of fear that a respectable number of users are still using cordova<7 ... do we have a numbers about that? do you know any other plugin where cordova >= 7 is a must?

So far there aren't such new limitation in the plugin since a long time, I don't want to arm a part of the users, you know what I mean, just want to be sure

2. Cool

**Comment by peterpeterparker** [comment]
Maybe could you improve the PR, like

    if cordova < 7 (could we check that from config.xml or other?)
       like before from config.xml
    else
       new from package.json

what do you think about this?

**Comment by keyz182** [comment]
To recreate:
Ensure you're logged into ionic with `ionic login`
```
ionic start myApp tabs
>Would you like to integrate your new app with Cordova to target native iOS and Android? Yes
>Install the free Ionic Pro SDK and connect your app? (Y/n) No
>Create a new app
cd myApp
ionic link
>Create a new app
>Enter a name
>Which git host would you like to use? Ionic Pro
npm i
ionic cordova prepare
ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication"
ionic cordova plugin add cordova-plugin-ionic --save --variable APP_ID="abcdefg" --variable CHANNEL_NAME="Channel"
ionic cordova platform add browser
```

Now `myApp/platforms/browser/www/plugins/cordova-plugin-facebook4/www/facebook-browser.js` should have "abcdefg" from ionic, not "123456789" from this plugin.

The regext appears to pick up the last match, so moving the facebook plugin entry in config.xml below the Ionic one works as a temporary fix.

Looking at Cordova docs it appears all the needed info is passed to the hook already, so no need to read files. I also checked, and this way will work back to at least cordova 5.

https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/#script-interface

Wrapping everything in:
```
module.exports = function(context) {
    ...
}
```

gives us access to the context variable, which looks like this: 
```
{
  "hook": "before_plugin_install",
  "scriptLocation": "c:\\script\\full\\path\\appBeforePluginInstall.js",
  "cmdLine": "The\\exact\\command\\cordova\\run\\with arguments",
  "opts": {
    "projectRoot":"C:\\path\\to\\the\\project",
    "cordova": {
      "platforms": ["android"],
      "plugins": ["plugin-withhooks"],
      "version": "0.21.7-dev"
    },
    "plugin": {
      "id": "plugin-withhooks",
      "pluginInfo": {
        ...
      },
      "platform": "android",
      "dir": "C:\\path\\to\\the\\project\\plugins\\plugin-withhooks"
    }
  },
  "cordova": {...}
}
```
I'll test now and try to get an update to this PR using this method instead.

**Comment by peterpeterparker** [comment]
@keyz182 awesome, thx a lot in advance for the enhancement 👍

**Comment by keyz182** [comment]
Looks like the `context` object didn't contain everything needed. It did contain the cordova version though, so I've added a check, if >= 7, use package.json, if <7 use config.xml.

**Comment by peterpeterparker** [comment]
understood, thx for the enhancement, cool 👍 

I'll try to have a look as soon as I can. If you don't hear something till the end of the week from my side, don't hesitate to ping me!

**Comment by peterpeterparker** [comment]
@keyz182 I had a look and try following your description of "how to reproduce the problem" and have got questions

1. could you explain me what you mean with:

> Now myApp/platforms/browser/www/plugins/cordova-plugin-facebook4/www/facebook-browser.js should have "abcdefg" from ionic, not "123456789" from this plugin.

in my opinion `facebook-browser.js` should contains `123456789` and not `abcdefg` as you says, that would be wrong no? respectively

    window.fbAsyncInit = function() {
        FB.init({
          appId      : 123456789,  // 123456789 is populated by the cordova after_prepare hook
          xfbml      : true,
         version    : 'v2.7'
       });

2. I tried with the current version of the plugin many times and I was not able to reproduce the problem, `facebook-browser.js` always contained the correct facebook APP_ID aka `123456789`

**Comment by keyz182** [comment]
> in my opinion facebook-browser.js should contains 123456789 and not abcdefg as you says, that would be wrong no? respectively

Yes, it should contain, 123456789, but for me does not. 

It seems that I cannot reliably reproduce the issues as I documented above - sorry.

What does work to reproduce though it to edit `config.xml` to ensure the facebook plugin is declared *before* the ionic one, as shown below. 
`
    <plugin name="cordova-plugin-facebook4" spec="^2.2.0">
        <variable name="APP_ID" value="1234567890" />
        <variable name="APP_NAME" value="myApp" />
        <variable name="ANDROID_SDK_VERSION" value="4.+" />
    </plugin>
    <plugin name="cordova-plugin-ionic" spec="4.1.7">
        <variable name="APP_ID" value="abcdefg" />
        <variable name="CHANNEL_NAME" value="production" />
        <variable name="UPDATE_METHOD" value="none" />
        <variable name="MAX_STORE" value="0" />
        <variable name="WARN_DEBUG" value="true" />
        <variable name="UPDATE_API" value="https://api.ionicjs.com" />
        <variable name="ROLLBACK_TIMEOUT" value="10" />
    </plugin>
`

**Comment by peterpeterparker** [comment]
thx for the feedback @keyz182 

1. ok so I understand correctly, the Facebook APP_ID should not be overwritten by the APP_ID of the Ionic plugin

2. before or after, whatever sort I use, the correct Facebook APP_ID ("123456789") is always correctly use and integrated to `facebook-browser.js`. Could you plz provide a sample repo to reproduce the problem?

**Comment by keyz182** [comment]
@peterpeterparker I'm right at the end of a project at the moment, so things are very busy now, as soon as I'm done, I'll get a repro-repo for you. If you want to close the issue, I can open a new one.

For anyone that does come across this issue in the mean-time, the simple workaround is to ensure the `cordova-plugin-facebook4` `<plugin>` entry appears after `cordova-plugin-ionic` in `config.xml`.

**Comment by peterpeterparker** [comment]
@keyz182 thx a lot, really appreciate it

no worries we could keep it open for me it's no problem. ping me when you are ready

**Comment by Andrewpk** [comment]
Reading through this, it looked like the end temporary solution was to make sure this plugin's config.xml entry was lower than others in the file to ensure its values were applied last. With corodova android 7.1.4 and latest cordova 8, this doesn't seem to help. Looks like the facebookconnect.xml file is always empty.

**Pull request closed without merging**
