### PR TITLE
Fixed issues with AppInvite callbacks on Android

### LINKED ISSUE #35: App crash when clicking back on App Invite dialog
09-09 15:53:08.388: E/AndroidRuntime(28564): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64213, result=-1, data=Intent { (has extras) }} to activity {be.xxxxxxxxxx.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(org.json.JSONObject)' on a null object reference
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4058)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4101)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread.access$1400(ActivityThread.java:177)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1497)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.os.Looper.loop(Looper.java:145)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at java.lang.reflect.Method.invoke(Native Method)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at java.lang.reflect.Method.invoke(Method.java:372)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
09-09 15:53:08.388: E/AndroidRuntime(28564): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(org.json.JSONObject)' on a null object reference
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.facebook.ConnectPlugin.handleError(ConnectPlugin.java:724)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.facebook.ConnectPlugin.access$4(ConnectPlugin.java:709)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.facebook.ConnectPlugin$6.onCancel(ConnectPlugin.java:223)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.facebook.share.widget.AppInviteDialog$1.onSuccess(AppInviteDialog.java:149)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.facebook.share.internal.ShareInternalUtility.handleActivityResult(ShareInternalUtility.java:174)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.facebook.share.widget.AppInviteDialog$2.onActivityResult(AppInviteDialog.java:159)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:82)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.facebook.ConnectPlugin.onActivityResult(ConnectPlugin.java:251)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:353)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.Activity.dispatchActivityResult(Activity.java:6549)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4054)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	... 10 more

If I comment 

            @Override
            public void onCancel() {
            //    FacebookOperationCanceledException e = new FacebookOperationCanceledException();
            //    handleError(e, showDialogContext);
            }

            @Override
            public void onError(FacebookException e) {
             //   Log.e("Activity", String.format("Error: %s", e.toString()));
              //  handleError(e, showDialogContext);
            }

if works

### PR DESCRIPTION
**Pull request by dtritus**
Fixes #35, #63, #85. Also, makes `picture` parameter optional, Facebook doesn't require it (https://developers.facebook.com/docs/app-invites/android#dialog_parameters)

### CODE REVIEW

**Comment by jeduan** [comment]
Thank you so much! Currently reviewing. @hirbod maybe you'd like to take a look?

**Comment by Hirbod** [comment]
@jeduan I'm happy you still looking for your issues. Thought you won't give me a response anymore.
I appreciate the work for @dtritus - but from what I see, it is not implemented like I did.

https://github.com/dtritus/cordova-plugin-facebook4/commit/eb8bbd21ed5afa5ad5ac3eee0c1cffa89d8d8acb#diff-c25cdc153106f171cfa0c5fc8fdc1ffdR351

It won't crash and will receive a callback, but no informations inside of it. Have a look at #59 

Triggerin a success-callback only cause "it can show" is useless.

**Comment by dtritus** [comment]
@Hirbod I didn't find any information about result format (looked at https://developers.facebook.com/docs/app-invites/android and https://developers.facebook.com/docs/reference/android/current/class/AppInviteDialog.Result/), so I just fixed issues with callbacks.
Also, success callback called on dialog close, not on dialog open. Personally for me, it's useful.

**Comment by jeduan** [comment]
@dtritus can you inspect what does the `Bundle` in `AppInviteDialog.Result` has?

**Comment by Hirbod** [comment]
I've was about to write exactly the same. @jeduan

**Comment by dtritus** [comment]
@jeduan Sorry, I don't have time for this.

**Comment by jeduan** [comment]
Welcome to my life! 😜

**Comment by Hirbod** [comment]
I post a 30$ bounty on it!

**Comment by dtritus** [comment]
I've added results to success callback. Should work in the same way as #59.
Also I've rebased pull request on top of master.

**Comment by Hirbod** [comment]
@dtritus send me your paypal email. I will send you that bounty.
@jeduan would you please merge this? We've waited so freaking long for that :)

**Pull request merged**
