### PR TITLE
fetchDeferredAppLink

### PR DESCRIPTION
**Pull request by jkassis**
improved this with error handling and sending deferred links back to the app where they can be handled in javascript first or sent to the browser and/or os. much better way of handling this.

### CODE REVIEW

**Comment by bericp1** [comment]
@jkassis Taking a look at the changeset, this looks ready to use. Have you tested it and is it working for you on iOS and Android? I'm thinking of just pulling the plugin from your repo instead for now until this is merged in.

Additionally (I'm sure you know this but I thought I'd just add) to get this approved for merging, I would suggest reverting the changes made in [`73ffc86`](https://github.com/jeduan/cordova-plugin-facebook4/pull/269/commits/73ffc86e86996c886fbae8f842620766b30a1294) to the following files since they're specific to your repo/environment:
 * `.gitignore`
 * `docs/android/README.md`
 * `package.json`

Thanks for your work on this!

**Comment by Hirbod** [comment]
as soon as @jkassis  fixed the problems pointed out by @bericp1 we're going to merge this

**Comment by shmuel-krakower** [comment]
hi @jkassis any plans to fix the minor points for the merge?

**Comment by FME-nstokoe** [comment]
Has anyone confirmed that these updates work?

**Comment by maktibab** [comment]
I haven't see deep link deferred function in the Android folder... only in the iOS.
This is not yet merge?

**Comment by bericp1** [comment]
@Hirbod, It looks like @nstokoe has prepared his own PR at #362 that's ready to merge.

**Pull request merged**
