### PR TITLE
Add "share_open_graph" features

### PR DESCRIPTION
**Pull request by Vahn84**
I've done this in a few minutes

### CODE REVIEW

**Comment by betorobson** [comment]
This PR popup facebook iOS authentication instead of webview facebook authentication?

**Comment by Vahn84** [comment]
Yes, it checks if it can open the native dialog, and defaults back to automatic (webview in most of the cases) if it can't

**Comment by Vahn84** [comment]
parameters can be arranged better than they are now

**Comment by betorobson** [comment]
I just tested it, actually it works fine in iOS simulator 9.3, although it still show a webview facebook form login on device. :-(

**Comment by Vahn84** [comment]
i've tested it on my iPhone 6s with iOS 9.3 and it works fine...i will dig into it to find what's the issue, can you tell me more about your configuration?

**Comment by Vahn84** [comment]
I've found where's the issue...this is not related to the open graph share code i've edited. This is due to the LoginManager.loginBehavior

I've tried setting it to "FBSDKLoginBehaviorNative"...but it was still going with the webview modal...

as of Facebook sdk source code 

`@abstract This is the default behavior, and indicates logging in through the native
   Facebook app may be used. **The SDK may still use Safari instead.**
   */
  FBSDKLoginBehaviorNative = 0,
`

The only thing that does work for my iPhone was setting it to "FBSDKLoginBehaviorSystemAccount".

It uses the account stored in phone settings if it find it, with the iOS system popup asking for permission to use it or not. If it doesn't find an account stored it falls back to the webview

**Comment by romuloctba** [comment]
hey, this seems cool, how is it going?

**Comment by noahcooper** [comment]
Open Graph Stories are deprecated by Facebook as of 2019.

This plugin is deprecated. See `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

**Pull request closed without merging**
