### PR TITLE
Updated share_open_graph.

### PR DESCRIPTION
**Pull request by DoruLa**
Added Open Graph objects and Open Graph actions. The options object provided to **showDialog** will have:

**method**: 'share_open_graph' - **Required**
**action**: Open Graph action name - **Required**
**action_properties**: A stringyfied JSON object containing action properties - Optional
**object**: A stringyfied JSON object containing Open Graph object properties. The og:type property is mandatory - **Required**

### CODE REVIEW

**Comment by DoruLa** [comment]
@jeduan Sorry, I'm a bit inexperienced. The only way I knew how to merge in all the commits was to start from scratch. I hope it is OK now.

**Comment by jeduan** [comment]
@DoruLa sorry you had to do that! Here's a way to do it next time: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by DoruLa** [comment]
@jeduan Thank you! I will look into it. :+1:

**Comment by anemitoff** [comment]
This pull request FAILS to add support for iOS!!!
This fact should at least be noted in the READ.ME documentation!

**Comment by Hirbod** [comment]
thx @anemitoff - added

**Pull request merged**
