### PR TITLE
Use of CocoaPods to fetch facebook sdk

### PR DESCRIPTION
**Pull request by pellaras**
Removed the bundled facebook sdk and reference CocoaPods ones.
Current facebook sdk version: 4.44.1
Added instructions on how to install CocoaPods
A few bugfixes and code cleaning as well

### CODE REVIEW

**Comment by matheo** [comment]
@pellaras did you publish this stuff?
I'm having issues building my `ios` app with this plugin, and I wonder if the `cocoapods` are working better.
I'm getting this exception:
```
App[24333:1173151] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FBSDKBasicUtility objectForJSONString:error:]: unrecognized selector sent to class 0x105fa14c0'
*** First throw call stack:
(
    0   CoreFoundation                      0x0000000109c096fb __exceptionPreprocess + 331
    1   libobjc.A.dylib                     0x000000010729bac5 objc_exception_throw + 48
    2   CoreFoundation                      0x0000000109c279b4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
    3   CoreFoundation                      0x0000000109c0e443 ___forwarding___ + 1443
    4   CoreFoundation                      0x0000000109c10238 _CF_forwarding_prep_0 + 120
    5   CordovaPlugins                      0x0000000105f1a5f7 +[FBSDKAppEventsUtility retrievePersistedAnonymousID] + 231
    6   CordovaPlugins                      0x0000000105f19a29 +[FBSDKAppEventsUtility anonymousID] + 47
    7   CordovaPlugins                      0x0000000105f2ab64 +[FBSDKAppEvents initialize] + 180
    8   libobjc.A.dylib                     0x000000010729c698 CALLING_SOME_+initialize_METHOD + 19
    9   libobjc.A.dylib                     0x000000010729ca2a initializeNonMetaClass + 269
    10  libobjc.A.dylib                     0x000000010729d54f _ZL24initializeAndMaybeRelockP10objc_classP11objc_objectR8mutex_ttILb0EEb + 144
    11  libobjc.A.dylib                     0x00000001072a33e2 lookUpImpOrForward + 205
    12  libobjc.A.dylib                     0x00000001072b10d4 _objc_msgSend_uncached + 68
    13  CordovaPlugins                      0x0000000105f1d30d +[FBSDKSettings _logIfSDKSettingsChanged] + 1227
    14  libobjc.A.dylib                     0x000000010729c698 CALLING_SOME_+initialize_METHOD + 19
    15  libobjc.A.dylib                     0x000000010729ca2a initializeNonMetaClass + 269
    16  libobjc.A.dylib                     0x000000010729d54f _ZL24initializeAndMaybeRelockP10objc_classP11objc_objectR8mutex_ttILb0EEb + 144
    17  libobjc.A.dylib                     0x00000001072a33e2 lookUpImpOrForward + 205
    18  libobjc.A.dylib                     0x00000001072b10d4 _objc_msgSend_uncached + 68
    19  CordovaPlugins                      0x0000000105efbee1 +[FBSDKApplicationDelegate load] + 33
    20  libobjc.A.dylib                     0x000000010729d317 call_load_methods + 691
    21  libobjc.A.dylib                     0x000000010729e814 load_images + 77
```
and after this one is fixed another one appears:
```
0   CoreFoundation                      0x000000010e4cf6fb __exceptionPreprocess + 331
    1   libobjc.A.dylib                     0x000000010bbcfac5 objc_exception_throw + 48
    2   CoreFoundation                      0x000000010e4ed9b4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
    3   CoreFoundation                      0x000000010e4d4443 ___forwarding___ + 1443
    4   CoreFoundation                      0x000000010e4d6238 _CF_forwarding_prep_0 + 120
    5   CordovaPlugins                      0x000000010a825c34 +[FBSDKServerConfigurationManager loadServerConfigurationWithCompletionBlock:] + 818
    6   CordovaPlugins                      0x000000010a830867 -[FBSDKApplicationDelegate application:didFinishLaunchingWithOptions:] + 223
    7   App                                 0x000000010a2dd48f
``` 
any idea or possible solution please? :)

**Comment by peterpeterparker** [comment]
@matheo the issue you are facing is https://github.com/jeduan/cordova-plugin-facebook4/issues/776 any help and PR to solve it is welcomed

**Comment by matheo** [comment]
@peterpeterparker this PR was cleaner, perhaps the version of the cocoapos needs to be updated.
@pellaras do you have some time to get this merged?

**Comment by pellaras** [comment]
@matheo This PR has the Facebook SDK 4.x which this plugin was initially written for. SDK 5.x introduced breaking changes that not all of them were addressed in the latest release of this plugin. Most notably the order of the parameters, are all closures were moved at the end.

Changing just the pods to Facebook SDK 5.x will have the same issues, as the current release.

**Comment by matheo** [comment]
@pellaras uh, can you help us to figure out the most notable problems ATM please please?

**Comment by peterpeterparker** [comment]
@pellaras could you update the branch to resolves the conflict and reference Cocoapods using a pod specs like? I'm ok to test it and merge it if ok afterwards, ping me

```
<podspec>
      <config>
        <source url="https://github.com/CocoaPods/Specs.git"/>
      </config>
      <pods use-frameworks="true">
        <pod name="FBSDKCoreKit" spec="5.0.2"/>
        <pod name="FBSDKLoginKit" spec="5.0.2"/>
        <pod name="FBSDKShareKit" spec="5.0.2"/>
      </pods>
    </podspec>
```

**Comment by peterpeterparker** [comment]
@pellaras I've created another PR for Cocoapods which I have now merged in Master (https://github.com/jeduan/cordova-plugin-facebook4/pull/792)

I see that you have other interesting features and improvements in your PR, could you like to split them in another separate PR so we just merge these please?

thx in advance for your help

**Comment by matheo** [comment]
Thanks @peterpeterparker!

**Comment by peterpeterparker** [comment]
@matheo my pleasure. it has been now released (v6.0.0 I thought it was useful to release it as major version).

like I said above, I think this PR contained also cool other stuffs, if someone or OP could provide them as separate PR, happy to merge them

**Comment by pellaras** [comment]
Thanks to both of of you!

Will try to get a PR with those changes and a few adjustments, as the podspec tag is only valid for cordova 9.x and not older versions.

**Pull request closed without merging**
