### PR TITLE
Update iOS SDKs to 4.11.0 and add quote sharing.

### PR DESCRIPTION
**Pull request by joshuarh**
Update to #186 using the 4.11.0 SDKs released on 4/11/16, with the ability to use the quote feature when using the share dialog.

### CODE REVIEW

**Comment by clarkgiguiere** [comment]
👍🏻

**Comment by clarkgiguiere** [comment]
@Hirbod?

**Comment by robertarnesson** [comment]
https://github.com/jeduan/cordova-plugin-facebook4/commit/61d454c278eec12a66d05f3337303d280cc6bf77

**Comment by joshuarh** [comment]
Does 61d454c include support for the quote attribute as in https://github.com/jeduan/cordova-plugin-facebook4/pull/219/commits/bad362b379b5b6f1dc5b11ac7d355cb089f78b81? If not, could we merge just that commit?

**Comment by robertarnesson** [comment]
No it does not, but you can send a new PR with just those changes. Also the android implementation is missing. Feel free to include a documentation update as well

**Pull request closed without merging**
