### PR TITLE
added better callbacks for appInvite on iOS

### PR DESCRIPTION
**Pull request by Hirbod**
Changed appInvite callbacks, you can now determine if the user pressed
done, cancel or really finished the invite. iOS only, no android know
how!

### CODE REVIEW

**Comment by Hirbod** [comment]
More details #59

**Comment by jeduan** [comment]
This looks great! Thanks @Hirbod. Can you just please remove the additional whitespace in the code?

**Comment by Hirbod** [comment]
Damn.. Xcode did this automagically :D. Will change in a sec

**Comment by Hirbod** [comment]
Any clue how I can do this with xcode without to deleting every line manully?

**Comment by Hirbod** [comment]
Seems like there no whitespaces, but I'm using Line-Endings (LF), I guess you're using CR ?

**Comment by jeduan** [comment]
Did you turn on Invisibles? (Editor -> Show Invisibles)

Also, make sure you have theses preferences turned on

**Comment by Hirbod** [comment]
Crap.. :D I turned on, but seems like it does not work. I will revert everything now and incorporate my changes with SublimeText...

**Comment by Hirbod** [comment]
Oh, no, actually it should be fine now, or not?

**Comment by Hirbod** [comment]
Hi @jeduan, I guess you need to revert this. Seems like my fork was not up to date, you deleted some of your code changes.

**Comment by jeduan** [comment]
reverted

**Comment by Hirbod** [comment]
I will resubmit in few minutes

**Pull request merged**
